### PR TITLE
tests: add id html attributes for cypress tests

### PR DESCRIPTION
**Pull request by AoNoOokami**
* Adds id html attributes on editor's clone and remove buttons.

Co-Authored-by: Alicia Zangger <alicia.zangger@rero.ch>

## Why are you opening this PR?

To make Cypress tests cleaner.

## Dependencies

My PR depends on the following PR(s):

* https://github.com/rero/rero-ils/pull/1595

## How to test?

Check id html attributes in template (clone and remove buttons).

## Code review check list

- [ ] Commit message template compliance.
- [ ] Commit message without typos.
- [ ] File names.
- [ ] Functions names.
- [ ] Functions docstrings.
- [ ] Unnecessary commited files?
- [ ] Extracted translations?

### CODE REVIEW

**Review by sebastiendeleze — APPROVED** [review]
OK, but I'm still not fan of adding attributes just for tests...

**Comment by iGormilhit** [comment]
@sebastiendeleze I can't remember if other solutions have been proposed, instead of specific ID HTML attributes. Does any other solution exists?

**Review by iGormilhit — COMMENTED** [review]
I prefer when HMTL is in capital characters (commit message). :slightly_smiling_face:

**Comment by AoNoOokami** [comment]
> I prefer when HMTL is in capital characters (commit message). slightly_smiling_face

Ok I'll correct that.

**Comment by AoNoOokami** [comment]
> @sebastiendeleze I can't remember if other solutions have been proposed, instead of specific ID HTML attributes. Does any other solution exists?

@sebastiendeleze @iGormilhit Adding id HTML attributes is the solution that was accepted after several discussions about Cypress good pratices to avoid instructions lake the following: `cy.get('#field-title > :nth-child(2) > :nth-child(1) > :nth-child(1) > :nth-child(1) > :nth-child(1) > :nth-child(1) > :nth-child(1) > ng-core-editor-dropdown-label-editor.ng-star-inserted > .d-block > .btn-group > .text-secondary')`

**Comment by iGormilhit** [comment]
@AoNoOokami Thanks for the answer. It's ok for me.

**Review by iGormilhit — APPROVED** [review]

**Review by zannkukai — APPROVED** [review]

**Pull request merged**
